name: CI - DockerHub Build&Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        python-version: "3.11"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build Docker image and tag with version|latest
      run: |
        VERSION=v1.0.${{ github.run_number }}
        docker build --no-cache -t amit1020/phishing-scan-platform-kube:$VERSION .
        docker tag amit1020/phishing-scan-platform-kube:$VERSION amit1020/phishing-scan-platform-kube:latest  # Tagging the image as latest
        
        

    - name: Push Docker image
      run: |
        VERSION=v1.0.${{ github.run_number }}
        docker push amit1020/phishing-scan-platform-kube:$VERSION
        docker push amit1020/phishing-scan-platform-kube:latest 





   