name: CI - DockerHub Build&Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        python-version: "3.11"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build Docker image
      run: |
        docker build -t mit1020/phishing-scan-platform-kube:latest .

    - name: Push Docker image
      run: |
        docker push mit1020/phishing-scan-platform-kube:latest 
